name: Elevators
author: Keehl
main: me.keehl.elevators.ElevatorsPlugin
api-version: 1.13
folia-supported: true
loadbefore: [SuperiorSkyblock2,Lands]
softdepend: [PlaceholderAPI,RedProtect,Vault,HolographicDisplays,GriefPrevention,GriefDefender,CMI,PlotSquared,BentoBox,DecentHolograms,FancyHolograms,ProtocolLib,WorldGuard,Protect,ItemsAdder,Oraxen,Nexo]

commands:
  elevators:
    description: Access elevators commands
    usage: /elevators
    aliases: [ele]
version: 5.0.0-beta.15